// GENERATED by tools/gen-watch-palettes.mjs — DO NOT EDIT BY HAND.
//
// Jr's palette list, resampled from the phone's own colour tables
// (src/assets/colormaps.ts) to 32 evenly spaced stops. Regenerate after
// changing a palette on the phone, or the two drift and a colour chosen there
// becomes unreachable here — which is exactly what the dead "Sync" option was
// papering over.
import Foundation

extension WFPalette {
  static let gqrx = WFPalette(id: "gqrx", name: "gqrx",
    hex: ["#000000", "#000000", "#000000", "#00000e", "#000024", "#00003a", "#000051", "#00006a", "#000080", "#08109b", "#1832ba", "#2853d8", "#3a78fb", "#578fdc", "#76a4b3", "#95b88a", "#b8d05c", "#d8e533", "#f7f90b", "#fff000", "#ffd900", "#ffc500", "#ffb000", "#ff9c00", "#ff8800", "#ff7100", "#ff5c00", "#ff4800", "#ff3300", "#ff1d00", "#ff0800", "#ffffff"])
  static let inferno = WFPalette(id: "inferno", name: "inferno",
    hex: ["#000004", "#040312", "#0b0724", "#160b39", "#230c4c", "#310a5c", "#3e0966", "#4d0d6c", "#5a116e", "#67166e", "#741a6e", "#801f6c", "#8f2469", "#9b2964", "#a82e5f", "#b43359", "#c13a50", "#cc4248", "#d74b3f", "#e05536", "#e9612b", "#ef6e21", "#f57b17", "#f8890c", "#fb9706", "#fca80d", "#fbb81d", "#f9c72f", "#f6d746", "#f2e865", "#f3f586", "#fcffa4"])
  static let turbo = WFPalette(id: "turbo", name: "turbo",
    hex: ["#30123b", "#392a73", "#4040a2", "#4559cb", "#476ee6", "#4682f8", "#4196ff", "#33adf7", "#25c0e7", "#1ad2d2", "#18e0bd", "#22ebaa", "#3cf58e", "#59fb73", "#79fe59", "#96fe44", "#affa37", "#c3f134", "#d7e535", "#e7d739", "#f5c53a", "#fcb336", "#fe9e2f", "#fc8725", "#f76f1a", "#ed5510", "#e2430a", "#d43305", "#c32503", "#ac1701", "#950d01", "#7a0403"])
  static let plasma = WFPalette(id: "plasma", name: "plasma",
    hex: ["#0d0887", "#220690", "#310597", "#41049d", "#4e02a2", "#5b01a5", "#6700a8", "#7501a8", "#8104a7", "#8d0ba5", "#9814a0", "#a21d9a", "#ad2793", "#b6308b", "#bf3984", "#c7427c", "#cf4c74", "#d6556d", "#dd5e66", "#e3685f", "#e97257", "#ef7c51", "#f3874a", "#f79143", "#fa9c3c", "#fca934", "#fdb52e", "#fdc229", "#fcce25", "#f9dd25", "#f5eb27", "#f0f921"])
  static let viridis = WFPalette(id: "viridis", name: "viridis",
    hex: ["#440154", "#470d60", "#48186a", "#482475", "#472e7c", "#453882", "#424186", "#3e4c8a", "#3a548c", "#365d8d", "#32658e", "#2e6d8e", "#2b758e", "#287d8e", "#25848e", "#228c8d", "#1f948c", "#1e9c89", "#20a386", "#25ab82", "#2eb37c", "#3aba76", "#48c16e", "#58c765", "#69cd5b", "#7fd34e", "#93d741", "#a8db34", "#bddf26", "#d5e21a", "#eae51a", "#fde725"])
  static let magma = WFPalette(id: "magma", name: "magma",
    hex: ["#000004", "#030312", "#0a0822", "#140e36", "#1e1149", "#2a115c", "#38106c", "#471078", "#54137d", "#601880", "#6d1d81", "#792282", "#882781", "#942c80", "#a1307e", "#ae347b", "#bd3977", "#ca3e72", "#d6456c", "#e24d66", "#ec5860", "#f3655c", "#f8745c", "#fb835f", "#fd9266", "#fea36f", "#feb27a", "#fec185", "#fecf92", "#fde0a1", "#fceeb0", "#fcfdbf"])
  static let classic = WFPalette(id: "classic", name: "Classic",
    hex: ["#000020", "#000027", "#00002e", "#00003c", "#00004a", "#000060", "#00007d", "#061ba5", "#135ad6", "#2c97ff", "#8fc8ff", "#f2f8ff", "#ffff90", "#ffff20", "#ffd107", "#fe9111", "#fe6d16", "#fe6d16", "#fe5f13", "#ff2f0a", "#ff0000", "#ff0000", "#ff0000", "#ea0000", "#d10000", "#ba0000", "#a90000", "#970000", "#850000", "#700000", "#5d0000", "#4a0000"])
  static let classicgreen = WFPalette(id: "classicgreen", name: "Classic Green",
    hex: ["#000000", "#000012", "#000024", "#000736", "#001642", "#00254f", "#003265", "#004081", "#00529c", "#0071bb", "#008fda", "#1eb3ce", "#54dda3", "#80ff80", "#80ff80", "#80ff80", "#9beb73", "#cbc75c", "#fba344", "#ff692b", "#ff2610", "#f70000", "#e10000", "#cc0000", "#bb0000", "#ab0000", "#9c0000", "#8c0000", "#7c0000", "#6a0000", "#5a0000", "#4a0000"])
  static let teejeez = WFPalette(id: "teejeez", name: "Teejeez",
    hex: ["#000000", "#000038", "#000070", "#0000af", "#0000e7", "#0020ff", "#0058ff", "#0097ff", "#00cfff", "#00fff7", "#00ffbf", "#00ff87", "#00ff48", "#00ff10", "#28ff00", "#60ff00", "#9fff00", "#d7ff00", "#ffef00", "#ffb700", "#ff7800", "#ff4000", "#ff0800", "#ff0030", "#ff0068", "#ff00a7", "#ff00df", "#ff18ff", "#ff50ff", "#ff8fff", "#ffc7ff", "#ffffff"])
  static let ha7ilm = WFPalette(id: "ha7ilm", name: "Ha7ilm",
    hex: ["#000000", "#0a1720", "#142e41", "#204765", "#2a5e85", "#35709b", "#427da8", "#518cb7", "#5e9ac5", "#67a2cd", "#578eb6", "#477ba0", "#356486", "#26516f", "#345e7c", "#507996", "#6e96b3", "#8ab1cd", "#a3c7d9", "#b9d2c2", "#d1dfa7", "#e6ea90", "#fcf578", "#ffe279", "#ffcb7e", "#ffb083", "#ff9887", "#f87d7d", "#e75f5f", "#d43d3d", "#c31e1e", "#b20000"])
  static let zoran = WFPalette(id: "zoran", name: "Zoran",
    hex: ["#000000", "#000110", "#000320", "#000432", "#000641", "#000751", "#000961", "#00277a", "#004892", "#006aaa", "#008cc3", "#00addb", "#00d3f6", "#05e3e6", "#0ce8be", "#13ed96", "#1bf269", "#22f741", "#29fc19", "#3afe00", "#5ffb00", "#80f800", "#a1f500", "#c2f200", "#e2ef00", "#ffe300", "#ffbe00", "#ff9900", "#ff7400", "#ff4a00", "#ff2500", "#ff0000"])
  static let kiwi = WFPalette(id: "kiwi", name: "Kiwi",
    hex: ["#000000", "#000042", "#000084", "#0000ce", "#000dff", "#0040ff", "#0073ff", "#00acff", "#00dfff", "#00ffdf", "#00ff8a", "#00ff35", "#33ff00", "#99ff00", "#ffff00", "#ffe100", "#ffbf00", "#ffa100", "#ff8300", "#ff6500", "#ff4400", "#ff2600", "#ff0800", "#ff000b", "#ff0019", "#ff0029", "#ff0037", "#ff0045", "#ff0054", "#ff0064", "#ff0072", "#ff0080"])
  static let cutesdr = WFPalette(id: "cutesdr", name: "CuteSDR",
    hex: ["#000000", "#00002f", "#00005f", "#000094", "#0000c4", "#0000f3", "#0023ff", "#0057ff", "#0085ff", "#00b4ff", "#00e2ff", "#00ffe8", "#00ffa2", "#00ff64", "#00ff27", "#17ff00", "#5aff00", "#96ff00", "#d2ff00", "#fff700", "#ffd200", "#ffb200", "#ff9200", "#ff7100", "#ff5100", "#ff2d00", "#ff0c00", "#ff0011", "#ff002c", "#ff004a", "#ff0065", "#ff0080"])
  static let sdrdx = WFPalette(id: "sdrdx", name: "SdrDx",
    hex: ["#000000", "#000033", "#000066", "#000090", "#0000a9", "#0000c3", "#0000dc", "#0000f9", "#1111ee", "#2828d7", "#3e3ec1", "#5555aa", "#6f6f91", "#85857a", "#9c9c63", "#b3b34d", "#cccc33", "#e3e31c", "#f9f906", "#ffcc00", "#ff8000", "#ff3c00", "#ff0909", "#ff4d4d", "#ff9191", "#ffdddd", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff"])
  static let kiwilinear = WFPalette(id: "kiwilinear", name: "Kiwi Linear",
    hex: ["#00ff00", "#08f708", "#10ef10", "#19e619", "#21de21", "#29d629", "#31ce31", "#3ac53a", "#42bd42", "#4ab54a", "#52ad52", "#5aa55a", "#639c63", "#6b946b", "#738c73", "#7b847b", "#847b84", "#8c738c", "#946b94", "#9c639c", "#a55aa5", "#ad52ad", "#b54ab5", "#bd42bd", "#c53ac5", "#ce31ce", "#d629d6", "#de21de", "#e619e6", "#ef10ef", "#f708f7", "#ff00ff"])
  static let electric = WFPalette(id: "electric", name: "Electric",
    hex: ["#000000", "#000018", "#000030", "#00004b", "#000063", "#00007b", "#000093", "#0000ae", "#0000c6", "#0000de", "#0000f6", "#000fff", "#002aff", "#0042ff", "#005aff", "#0072ff", "#008dff", "#00a5ff", "#00bdff", "#00d5ff", "#00f0ff", "#09ffff", "#21ffff", "#39ffff", "#51ffff", "#6cffff", "#84ffff", "#9cffff", "#b4ffff", "#cfffff", "#e7ffff", "#ffffff"])
  static let jet = WFPalette(id: "jet", name: "Jet",
    hex: ["#00008f", "#0000a1", "#0000b2", "#0000c6", "#0000d7", "#0000e9", "#0000fb", "#0023ff", "#004bff", "#0073ff", "#009bff", "#00c3ff", "#00f0ff", "#19ffe6", "#41ffbe", "#69ff96", "#96ff69", "#beff41", "#e6ff19", "#fff000", "#ffc300", "#ff9b00", "#ff7300", "#ff4b00", "#ff2300", "#fa0000", "#e60000", "#d20000", "#be0000", "#a80000", "#940000", "#800000"])
  static let websdr = WFPalette(id: "websdr", name: "WebSDR",
    hex: ["#000000", "#00000a", "#000014", "#00001f", "#000029", "#000033", "#00003d", "#000049", "#090056", "#29006c", "#490082", "#690098", "#8d00b1", "#ad00c7", "#cd00dd", "#ed00f3", "#ff12f3", "#ff32dd", "#ff52c7", "#ff72b1", "#ff9698", "#ffb682", "#ffd66c", "#fff656", "#ffff60", "#ffff78", "#ffff8e", "#ffffa4", "#ffffba", "#ffffd3", "#ffffe9", "#ffffff"])
  static let vivid = WFPalette(id: "vivid", name: "Vivid",
    hex: ["#000000", "#040013", "#070021", "#0a0029", "#11002b", "#1b0033", "#27003b", "#360143", "#40014f", "#451263", "#462f7b", "#3e4887", "#33628d", "#29788e", "#228e8d", "#25a286", "#3cb775", "#62ca5f", "#98d73d", "#cdeb2c", "#f8f622", "#fce018", "#fed227", "#feb92f", "#fe9029", "#f7721c", "#e95410", "#da3907", "#d02f04", "#b91f02", "#a61401", "#980e01"])
  static let temper = WFPalette(id: "temper", name: "Temper",
    hex: ["#000000", "#030114", "#080326", "#110936", "#261136", "#34133f", "#3e114e", "#4a1667", "#53207d", "#592c91", "#5d3da0", "#5e4eab", "#5f62b4", "#6171b9", "#6680bc", "#6d8fbf", "#799ec2", "#89acc5", "#9bb8c8", "#aec3cd", "#c6c0ba", "#d2b6a3", "#cda58c", "#c99579", "#c48469", "#be705c", "#b75f55", "#ad5051", "#a34150", "#943250", "#852750", "#741e4f"])
  static let smoke = WFPalette(id: "smoke", name: "Smoke",
    hex: ["#000000", "#040404", "#070707", "#0c0c0c", "#0f0f0f", "#151515", "#1d1d1d", "#252525", "#2d2d2d", "#343434", "#3c3c3c", "#434343", "#4b4b4b", "#535353", "#5a5a5a", "#626262", "#6a6a6a", "#727272", "#7c7c7c", "#8f8f8f", "#a4a4a4", "#b7b7b7", "#c9c9c9", "#d2d2d2", "#dadada", "#e2e2e2", "#eaeaea", "#f0f0f0", "#f3f3f3", "#f8f8f8", "#fbfbfb", "#ffffff"])
  static let grey = WFPalette(id: "grey", name: "Greyscale",
    hex: ["#000000", "#080808", "#101010", "#191919", "#212121", "#292929", "#313131", "#3a3a3a", "#424242", "#4a4a4a", "#525252", "#5a5a5a", "#636363", "#6b6b6b", "#737373", "#7b7b7b", "#848484", "#8c8c8c", "#949494", "#9c9c9c", "#a5a5a5", "#adadad", "#b5b5b5", "#bdbdbd", "#c5c5c5", "#cecece", "#d6d6d6", "#dedede", "#e6e6e6", "#efefef", "#f7f7f7", "#ffffff"])
  static let blackhot = WFPalette(id: "blackhot", name: "Black Hot",
    hex: ["#ffffff", "#f7f7f7", "#efefef", "#e6e6e6", "#dedede", "#d6d6d6", "#cecece", "#c5c5c5", "#bdbdbd", "#b5b5b5", "#adadad", "#a5a5a5", "#9c9c9c", "#949494", "#8c8c8c", "#848484", "#7b7b7b", "#737373", "#6b6b6b", "#636363", "#5a5a5a", "#525252", "#4a4a4a", "#424242", "#3a3a3a", "#313131", "#292929", "#212121", "#191919", "#101010", "#080808", "#000000"])
  static let nightvision = WFPalette(id: "nightvision", name: "Night Vision",
    hex: ["#000000", "#040000", "#080000", "#0d0000", "#120000", "#170000", "#1c0000", "#240000", "#2b0000", "#330000", "#3d0000", "#470000", "#540000", "#610000", "#6f0000", "#7f0000", "#910000", "#a20000", "#b10000", "#c00000", "#d00202", "#dc0707", "#e70d0d", "#f11717", "#f62828", "#fd3b3b", "#ff4f4f", "#ff6565", "#ff7b7b", "#ff9898", "#ffb2b2", "#ffcccc"])
  static let sonar = WFPalette(id: "sonar", name: "Sonar Green",
    hex: ["#000000", "#000300", "#000600", "#000900", "#001000", "#001600", "#001d00", "#002700", "#002f00", "#003900", "#004300", "#004d00", "#005b00", "#006900", "#007600", "#008700", "#009b00", "#00ab00", "#00b700", "#00c300", "#00d200", "#00e400", "#00f500", "#14ff14", "#40ff40", "#71ff71", "#92ff92", "#acffac", "#c6ffc6", "#d7ffdc", "#e3ffed", "#efffff"])
  static let sonarorange = WFPalette(id: "sonarorange", name: "Sonar Orange",
    hex: ["#000000", "#040100", "#090300", "#0e0400", "#130600", "#170700", "#1c0900", "#240c00", "#2b0f00", "#331200", "#3d1500", "#471900", "#541e00", "#602300", "#6d2700", "#7d2e00", "#8f3600", "#a03d00", "#ae4400", "#bd4b00", "#cc5300", "#d75b00", "#e26300", "#ec6e05", "#f37a10", "#fc881c", "#ff962f", "#ffa545", "#ffb55b", "#ffc981", "#ffdda7", "#fff0cc"])

  /// Every palette the phone offers, in the phone's own order.
  static let all: [WFPalette] = [
    .gqrx,
    .inferno,
    .turbo,
    .plasma,
    .viridis,
    .magma,
    .classic,
    .classicgreen,
    .teejeez,
    .ha7ilm,
    .zoran,
    .kiwi,
    .cutesdr,
    .sdrdx,
    .kiwilinear,
    .electric,
    .jet,
    .websdr,
    .vivid,
    .temper,
    .smoke,
    .grey,
    .blackhot,
    .nightvision,
    .sonar,
    .sonarorange,
  ]
}
