/**
 * dotField.ts — what the DOT Display's mode box and frequency unit SHOW, dot by dot (2026-10-06, Stuart: "Dot matrix
 * needs to also have the same treatment [as VCR], except being dot matrix means a lot more flexibility").
 *
 * VCR got FIXED 14-segment fields (constants/segField.ts, components/SegField.tsx). DOT gets the same four things as
 * true DOT-MATRIX fields, drawn by components/DotField.tsx: a fixed grid of 5 × 7 cells with EVERY unlit dot there as
 * a ghost (text colour α .10), the lit dots in the text colour with its glow.
 *
 * ★★★ ONE DOT, DOTO'S DOT. The cells light exactly the dots the Doto font lights — DOTO_GLYPHS below is read out of
 *   assets/fonts/Doto-Black.ttf by scripts/gen_dot_glyphs.mjs (and `--check` holds the two equal). Doto is a dot grid
 *   in its own units: every dot a 90 × 90 SQUARE centred on 50 + 100 k, columns 0 … 4 and rows 0 … 6 above the
 *   baseline, on a 600-unit advance. So at font size F its dot pitch is F × 0.1 (DOT_PITCH_EM), its dot 0.9 of that
 *   (DOT_SIZE), and its cell five dots and one dead column wide (DOT_ADV). A field here at pitch F × 0.1 is the
 *   Doto text it replaces, dot for dot — the same height, the same dots, the same spacing — with the ghosts added.
 *   ★ The cell is MEASURED from the font's outlines, not its spec (memory station_strip_layout_2026_10_03: the
 *     spec's 0.6 em advance was not what iOS drew; the dot grid inside the glyph is what this needs, and that is
 *     the outline's own coordinates).
 *
 * The fields (all FIXED width — nothing moves when the value or the mode changes):
 *
 *   THE MODE FIELD   DOT_MODE_CELLS (10) cells. ★ 2026-10-06: a PLAIN mode is one tight word on the plain cell pitch
 *                    ("AM", "MESHTASTIC" — no colon column); with a decoder: the demod right-aligned in three, a COLON COLUMN of
 *                    its own (two dots wide — Doto Black's colon is a heavy cluster, so 2 × 2 blocks, not single
 *                    dots), then seven cells: "USB:RTTY", "USB:WHISPER", "MESHTASTIC". In WFM the last three
 *                    cells' room is the STEREO RINGS — drawn in dots on the same pitch (DOT_RINGS); in every other
 *                    mode that room is cells. Over-long names step through a cell at a time (segField's rules —
 *                    the cell layout is segModeCells', shared, so the two Displays cannot disagree).
 *   THE READOUT      ten cells, "S9+27 dBFS": the value in cells 0 … 4, a space, then d B F S. A real S (not VCR's
 *                    5), a real plus and minus, full digits (no ±1 half-digit: −120 has a cell of its own).
 *                      S-meter   "S9+27" → S 9 + 2 7 · dB          ("S7" lights no unit)
 *                      dBFS      " -73"  → … dBFS
 *                      SNR       "  24"  → … dB
 *                      dBf       " 120"  → … dBf — a real lower-case f in the F cell (FM-DX's unit)
 *                    Numbers are right-aligned to cell 4 and the over-S9 digits right-aligned under the "+", so a
 *                    reading never hops between columns as it changes.
 *   THE UNIT         three cells beside the frequency digits, RIGHT-aligned: "kHz", "MHz", " Hz" — spelled
 *                    properly, because a dot matrix has lower case (a 14-segment display does not; VCR's capitals
 *                    were that display's compromise, not a rule).
 *
 * ★ Pure: no React, no runtime imports — scripts/test_faceplate_dotfield.ts runs it under plain Node.
 */

/** Doto's dot pitch, em (100 units of a 1000-unit em). */
export const DOT_PITCH_EM = 0.1;
/** A dot's side, in pitches — Doto Black's 90-unit square. */
export const DOT_SIZE = 0.9;
/** A cell: five dots by seven, and one dead column after it (Doto's 600-unit advance). */
export const DOT_COLS = 5;
export const DOT_ROWS = 7;
export const DOT_ADV = 6;

/** The pitch (pt) for Doto text at `fontSize` — what a field takes to sit on the same dots as that text. */
export const dotPitch = (fontSize: number) => fontSize * DOT_PITCH_EM;

/**
 * ★★ DOTO'S OWN DOTS: every printable ASCII glyph that sits inside 5 × 7, as rows top first ('#' lit). Generated by
 * scripts/gen_dot_glyphs.mjs from assets/fonts/Doto-Black.ttf — do not hand-edit; `--check` fails if one drifts.
 */
export const DOTO_GLYPHS: Readonly<Record<string, string>> = {
  "0": '..#.. .#.#. #...# #...# #...# .#.#. ..#..',
  "1": '..#.. .##.. #.#.. ..#.. ..#.. ..#.. #####',
  "2": '.###. #...# ....# ..##. .#... #.... #####',
  "3": '##### ....# ...#. ..##. ....# #...# .###.',
  "4": '...#. ..##. .#.#. #..#. ##### ...#. ...#.',
  "5": '##### #.... #.##. ##..# ....# #...# .###.',
  "6": '..##. .#... #.... #.##. ##..# #...# .###.',
  "7": '##### ....# ...#. ...#. ..#.. .#... .#...',
  "8": '.###. #...# #...# .###. #...# #...# .###.',
  "9": '.###. #...# #..## .##.# ....# ...#. .##..',
  "!": '..#.. ..#.. ..#.. ..#.. ..#.. ..... ..#..',
  "\"": '.#.#. .#.#. .#.#. ..... ..... ..... .....',
  "#": '.#.#. .#.#. ##### .#.#. ##### .#.#. .#.#.',
  "$": '..#.. .###. #.#.. .###. ..#.# .###. ..#..',
  "%": '.#..# #.#.# .#.#. ..#.. .#.#. #.#.# #..#.',
  "&": '.#... #.#.. #.#.. .#... #.#.# #..#. .##.#',
  "'": '..#.. ..#.. ..#.. ..... ..... ..... .....',
  "(": '...#. ..#.. .#... .#... .#... ..#.. ...#.',
  ")": '.#... ..#.. ...#. ...#. ...#. ..#.. .#...',
  "*": '..... #...# .#.#. ##### .#.#. #...# .....',
  "+": '..... ..#.. ..#.. ##### ..#.. ..#.. .....',
  "-": '..... ..... ..... ##### ..... ..... .....',
  "/": '....# ....# ...#. ..#.. .#... #.... #....',
  "<": '....# ...#. ..#.. .#... ..#.. ...#. ....#',
  "=": '..... ..... ##### ..... ##### ..... .....',
  ">": '.#... ..#.. ...#. ....# ...#. ..#.. .#...',
  "?": '.###. #...# ...#. ..#.. ..#.. ..... ..#..',
  "@": '.###. #...# #..## #.#.# #.##. #.... .###.',
  "A": '..#.. .#.#. #...# #...# ##### #...# #...#',
  "B": '####. .#..# .#..# .###. .#..# .#..# ####.',
  "C": '.###. #...# #.... #.... #.... #...# .###.',
  "D": '####. .#..# .#..# .#..# .#..# .#..# ####.',
  "E": '##### #.... #.... ####. #.... #.... #####',
  "F": '##### #.... #.... ####. #.... #.... #....',
  "G": '.###. #...# #.... #.... #..## #...# .###.',
  "H": '#...# #...# #...# ##### #...# #...# #...#',
  "I": '.###. ..#.. ..#.. ..#.. ..#.. ..#.. .###.',
  "J": '..### ...#. ...#. ...#. ...#. #..#. .##..',
  "K": '#...# #..#. #.#.. ##... #.#.. #..#. #...#',
  "L": '#.... #.... #.... #.... #.... #.... #####',
  "M": '#...# #...# ##.## #.#.# #...# #...# #...#',
  "N": '#...# #...# ##..# #.#.# #..## #...# #...#',
  "O": '.###. #...# #...# #...# #...# #...# .###.',
  "P": '####. #...# #...# ####. #.... #.... #....',
  "R": '####. #...# #...# ####. #.#.. #..#. #...#',
  "S": '.###. #...# #.... .###. ....# #...# .###.',
  "T": '##### ..#.. ..#.. ..#.. ..#.. ..#.. ..#..',
  "U": '#...# #...# #...# #...# #...# #...# .###.',
  "V": '#...# #...# #...# .#.#. .#.#. .#.#. ..#..',
  "W": '#...# #...# #...# #.#.# #.#.# ##.## #...#',
  "X": '#...# #...# .#.#. ..#.. .#.#. #...# #...#',
  "Y": '#...# #...# .#.#. ..#.. ..#.. ..#.. ..#..',
  "Z": '##### ....# ...#. ..#.. .#... #.... #####',
  "[": '.###. .#... .#... .#... .#... .#... .###.',
  "\\": '#.... #.... .#... ..#.. ...#. ....# ....#',
  "]": '.###. ...#. ...#. ...#. ...#. ...#. .###.',
  "^": '..#.. .#.#. #...# ..... ..... ..... .....',
  "a": '..... ..... .###. ....# .#### #...# .####',
  "b": '#.... #.... #.##. ##..# #...# ##..# #.##.',
  "c": '..... ..... .###. #...# #.... #...# .###.',
  "d": '....# ....# .##.# #..## #...# #..## .##.#',
  "e": '..... ..... .###. #...# ##### #.... .###.',
  "f": '..##. .#..# .#... ####. .#... .#... .#...',
  "h": '#.... #.... #.##. ##..# #...# #...# #...#',
  "i": '..#.. ..... .##.. ..#.. ..#.. ..#.. .###.',
  "k": '#.... #.... #...# #..#. ###.. #..#. #...#',
  "l": '.##.. ..#.. ..#.. ..#.. ..#.. ..#.. .###.',
  "m": '..... ..... ##.#. #.#.# #.#.# #.#.# #...#',
  "n": '..... ..... #.##. ##..# #...# #...# #...#',
  "o": '..... ..... .###. #...# #...# #...# .###.',
  "r": '..... ..... #.##. ##..# #.... #.... #....',
  "s": '..... ..... .###. #.... .###. ....# ####.',
  "t": '.#... .#... ####. .#... .#... .#..# ..##.',
  "u": '..... ..... #...# #...# #...# #..## .##.#',
  "v": '..... ..... #...# #...# .#.#. .#.#. ..#..',
  "w": '..... ..... #...# #...# #.#.# #.#.# .#.#.',
  "x": '..... ..... #...# .#.#. ..#.. .#.#. #...#',
  "z": '..... ..... ##### ...#. ..#.. .#... #####',
  "{": '...## ..#.. ...#. .##.. ...#. ..#.. ...##',
  "|": '..#.. ..#.. ..#.. ..#.. ..#.. ..#.. ..#..',
  "}": '.##.. ...#. ..#.. ...## ..#.. ...#. .##..',
  "~": '.#..# #.#.# #..#. ..... ..... ..... .....',
};

/**
 * The glyphs Doto draws OUTSIDE 5 × 7 (Black's heavy ':' and '.' clusters hang below the baseline; Q's tail and the
 * descenders g j p q y do too), drawn the way a 5 × 7 character ROM draws them. The descenders fall back to their
 * capitals (dotChar) — no label the mode box shows has one.
 */
export const DOT_EXTRA_GLYPHS: Readonly<Record<string, string>> = {
  ':': '..... .##.. .##.. ..... .##.. .##.. .....',
  '.': '..... ..... ..... ..... ..... .##.. .##..',
  'Q': '.###. #...# #...# #...# #.#.# #..#. .##.#',
};

/** A cell's glyph rows for `ch` (top first), or null for a dark cell. */
export function dotGlyph(ch: string): string | null {
  return DOTO_GLYPHS[ch] ?? DOT_EXTRA_GLYPHS[ch] ?? null;
}
/** `ch` as a cell the display can light: itself, else its capital (the descenders), else '?'; a space is dark (''). */
export function dotChar(ch: string): string {
  if (ch === ' ' || ch === '') return '';
  if (dotGlyph(ch)) return ch;
  const up = ch.toUpperCase();
  return dotGlyph(up) ? up : '?';
}
/** Every glyph a field can light — the lit atlas (components/DotField). */
export const DOT_ALPHABET: string = [...Object.keys(DOTO_GLYPHS), ...Object.keys(DOT_EXTRA_GLYPHS)].join('');

/** Text → cells, one char per cell ('' = dark) — the ToCells segModeCells takes. */
export const toDotCells = (text: string): string[] => [...text].map(dotChar);

/** A bitmap's lit dots as [col, row] pairs. */
export function bitmapDots(rows: string): Array<[number, number]> {
  const out: Array<[number, number]> = [];
  rows.split(' ').forEach((r, y) => [...r].forEach((c, x) => { if (c === '#') out.push([x, y]); }));
  return out;
}

// ── The mode field ───────────────────────────────────────────────────────────

/** Cells in the mode field (= segField SEG_MODE_CELLS: the same labels must fit both Displays). */
export const DOT_MODE_CELLS = 10;
/** The demod's cells; the colon column follows them. */
export const DOT_DEMOD_CELLS = 3;
/** The colon column: two dots wide, plus its own dead column (the dead column before it is the demod cell's). */
export const DOT_COLON_W = 2;
/** The colon column's dots (2 wide × 7, top row first): two 2 × 2 blocks, the 5 × 7 ROM colon's. */
export const DOT_COLON = '.. ## ## .. ## ## ..';
/** The stereo rings' slot, in cells, at the field's right-hand end (WFM only). */
export const DOT_STEREO_CELLS = 3;

/** Cell i's first dot column in the mode field: the colon column sits between cell 2 and cell 3. */
export const dotModeCellCol = (i: number) => i * DOT_ADV + (i >= DOT_DEMOD_CELLS ? DOT_COLON_W + 1 : 0);
/** The colon column's first dot column. */
export const DOT_COLON_COL = DOT_DEMOD_CELLS * DOT_ADV;
/** The mode field's width in dot columns (no trailing dead column). */
export const DOT_MODE_COLS = dotModeCellCol(DOT_MODE_CELLS - 1) + DOT_COLS;

/**
 * ★ The stereo rings in dots: two seven-dot rings, the second four columns on (StereoIcon's 0.62 × size), crossing
 * in a lens. On the field's own pitch, centred in the three-cell slot on whole columns — so they sit on the same dot
 * grid as the letters beside them. Ghosted as their own shape (an annunciator, like StereoMark), lit with the pilot.
 */
export const DOT_RINGS = '..###.###.. .#...#...#. #...#.#...# #...#.#...# #...#.#...# .#...#...#. ..###.###..';
export const DOT_RINGS_W = 11;
/** The rings' first dot column in the mode field. */
export const DOT_RINGS_COL = (() => {
  const x0 = dotModeCellCol(DOT_MODE_CELLS - DOT_STEREO_CELLS);
  return x0 + Math.floor((DOT_MODE_COLS - x0 - DOT_RINGS_W) / 2);
})();

// ── The readout ──────────────────────────────────────────────────────────────

/** The readout's cells: value (0 … 4), a space, d B F S. */
export const DOT_READ_CELLS = 10;
export const DOT_READ_COLS = DOT_READ_CELLS * DOT_ADV - 1;

export interface DotReadingCells {
  /** Ten cells, '' = dark: the value, then the unit's d B F/f S as lit. */
  cells: string[];
}

const DARK10 = (): string[] => Array<string>(DOT_READ_CELLS).fill('');

/**
 * The reading text (meters.ts formatReading: "S9+27", "S7", "-73dB", "24db", "120 dBf") → the readout's cells.
 * `unit` is the readout setting; a text that says dBf (FM-DX's static label) is dBf whatever the setting.
 */
export function dotReadingCells(text: string, unit: 'snr' | 'smeter' | 'dbfs' | 'dbf'): DotReadingCells {
  const cells = DARK10();
  const t = text.trim();
  const s = /^S(\d)(?:\+(\d+))?$/i.exec(t);
  if (s) {
    const over = s[2] ? Math.min(99, parseInt(s[2], 10)) : 0;
    cells[0] = 'S'; cells[1] = s[1];
    if (over > 0) {
      cells[2] = '+';
      if (over >= 10) cells[3] = String(Math.floor(over / 10));
      cells[4] = String(over % 10);
      cells[6] = 'd'; cells[7] = 'B';
    }
    return { cells };
  }
  const n = /^(-?\d+)\s*(dBf|dB)?$/i.exec(t);
  if (!n) return { cells };
  const u = /^dBf$/.test(n[2] ?? '') ? 'dbf' : unit === 'smeter' ? 'dbfs' : unit;
  // ★ Four cells reach −999 … 9999; nothing the meters produce comes near it.
  const v = Math.max(-999, Math.min(9999, parseInt(n[1], 10)));
  const digits = [...String(v)];
  digits.forEach((d, k) => { cells[5 - digits.length + k] = d; });
  cells[6] = 'd'; cells[7] = 'B';
  if (u === 'dbfs') { cells[8] = 'F'; cells[9] = 'S'; }
  if (u === 'dbf') cells[8] = 'f';
  return { cells };
}

/** The squelch's word in the readout's cells — right-aligned with the numbers. */
export const DOT_READ_SQL: readonly string[] = ['', '', 'S', 'Q', 'L', '', '', '', '', ''];

// ── The frequency unit ───────────────────────────────────────────────────────

/** The unit's cells: "kHz" / "MHz" — the longest unit the readout shows. */
export const DOT_UNIT_CELLS = 3;
export const DOT_UNIT_COLS = DOT_UNIT_CELLS * DOT_ADV - 1;

/** The frequency unit → its cells, case KEPT and RIGHT-aligned in a fixed three ('' = dark). */
export function dotUnitCells(unit: string): string[] {
  const u = toDotCells(unit.trim()).slice(-DOT_UNIT_CELLS);
  return [...Array<string>(DOT_UNIT_CELLS - u.length).fill(''), ...u];
}

/**
 * ★ The unit's pitch: HALF the frequency digits' (Doto at `freqFont` → freqFont × 0.1), so the unit's dots fall on
 * the digits' own grid, every other one — a finer field on the same glass, the way a real VFD sets its small legend
 * beside its big digits — and never wider than `columnW`, the label column it replaces, so the digits beside it
 * sit exactly where they did.
 */
export const dotUnitPitch = (freqFont: number, columnW: number) =>
  Math.min(dotPitch(freqFont) / 2, columnW / DOT_UNIT_COLS);
