#!/usr/bin/env bash
# ★★★ PUT THE CANONICAL MAP DATA WHERE EACH ARTEFACT SERVES IT FROM.
#
# assets/mapdata/v1 is the ONE source, generated by scripts/gen-map-data.mjs. Everything else gets
# a copy at package/deploy time and NONE of those copies are committed -- two committed copies of a
# 48 MB dataset is 48 MB of drift waiting to happen, and the stale one always wins somewhere.
#
# ★★ RUN THIS BEFORE `wrangler deploy` IN directory/. A deploy of a stale copy looks identical to a
#    deploy of a fresh one, right up until a layer is missing on the live site.
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
src="$root/assets/mapdata/v1"
[ -f "$src/index.json" ] || { echo "sync-mapdata: $src/index.json missing — run: node scripts/gen-map-data.mjs" >&2; exit 1; }

dest="$root/directory/public/mapdata/v1"
mkdir -p "$dest"
rsync -a --delete "$src/" "$dest/"
n=$(ls -1 "$dest" | wc -l | tr -d ' ')
# ★ Verify the ARTEFACT, not the command: a copy that silently moved nothing is the failure mode.
[ "$n" -ge 20 ] || { echo "sync-mapdata: only $n files landed in $dest — refusing to call that a sync." >&2; exit 1; }
echo "sync-mapdata: $n files -> directory/public/mapdata/v1"

# ★★★ AND THE APP CARRIES ITS OWN COPY OF THE BUNDLED PACK, because the app is the map source for
#  every engine it drives (an UberSDR/KiwiSDR has no /mapdata/v1/ at all). Same rule, same failure
#  mode: a stale embedded pack looks exactly like a fresh one until a layer is wrong in the app.
node "$root/scripts/gen-mapdata-source.mjs"
