#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>

@interface RCT_EXTERN_MODULE(VibePowerModule, RCTEventEmitter)
RCT_EXTERN_METHOD(startAudioEngine:(NSString *)baseUrl frequency:(NSInteger)frequency mode:(NSString *)mode uuid:(NSString *)uuid password:(NSString *)password)
RCT_EXTERN_METHOD(stopAudioEngine)
RCT_EXTERN_METHOD(startExternalAudio:(nonnull NSNumber *)sampleRate pauseMode:(NSString *)pauseMode)
RCT_EXTERN_METHOD(pushExternalPcm:(NSString *)base64 sampleRate:(nonnull NSNumber *)sampleRate channels:(nonnull NSNumber *)channels)
// VibeServer compressed audio — one Opus packet per call. See pushExternalOpus.
RCT_EXTERN_METHOD(pushExternalOpus:(NSString *)base64 sampleRate:(nonnull NSNumber *)sampleRate channels:(nonnull NSNumber *)channels)
RCT_EXTERN_METHOD(stopExternalAudio)
// ★ The LOCAL audio pump — iOS reads /ws/audio natively now, as Android always has, so no
//   packet crosses the bridge and nothing is base64-encoded on the JS thread.
//   Names match the Android module exactly, so LocalAudioPlayer's native branch works unchanged.
RCT_EXTERN_METHOD(startLocalAudio:(NSString *)host port:(nonnull NSNumber *)port initialTune:(NSString *)initialTune authSuffix:(NSString *)authSuffix wsBase:(NSString *)wsBase)
RCT_EXTERN_METHOD(sendLocalTune:(NSString *)json)
RCT_EXTERN_METHOD(stopLocalAudio)
RCT_EXTERN_METHOD(startFmdxAudio:(NSString *)baseUrl)
RCT_EXTERN_METHOD(stopFmdxAudio)
RCT_EXTERN_METHOD(revive)
RCT_EXTERN_METHOD(audioStaleness:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(setSystemVolume:(nonnull NSNumber *)v)
RCT_EXTERN_METHOD(getSystemVolume:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(sendTuneCommand:(NSInteger)frequency mode:(NSString *)mode)
RCT_EXTERN_METHOD(sendBandwidth:(NSInteger)low high:(NSInteger)high)
RCT_EXTERN_METHOD(setStep:(NSInteger)hz)
RCT_EXTERN_METHOD(setInstanceName:(NSString *)name)
RCT_EXTERN_METHOD(setMuted:(BOOL)muted)
RCT_EXTERN_METHOD(setVolume:(double)volume)
RCT_EXTERN_METHOD(startRecording:(nonnull NSNumber *)frequency mode:(NSString *)mode resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(stopRecording:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(shareRecording:(NSString *)path)
RCT_EXTERN_METHOD(getNativeCrash:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(clearNativeCrash)
RCT_EXTERN_METHOD(getDeviceInfo:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(setNrMode:(NSString *)mode)
RCT_EXTERN_METHOD(setNoiseBlanker:(BOOL)on)
RCT_EXTERN_METHOD(setNotch:(BOOL)on)
RCT_EXTERN_METHOD(setSquelchOpen:(BOOL)open)
RCT_EXTERN_METHOD(sendAudioCommand:(NSString *)json)
RCT_EXTERN_METHOD(setNowPlaying:(NSString *)title artist:(NSString *)artist)
RCT_EXTERN_METHOD(setMediaSkipMode:(NSString *)mode)
RCT_EXTERN_METHOD(setBrowseItems:(NSString *)json)
RCT_EXTERN_METHOD(setReconnectFailed:(BOOL)failed)
RCT_EXTERN_METHOD(setDefaultInstance:(NSString *)name)
RCT_EXTERN_METHOD(setVoiceConnected:(BOOL)connected)
RCT_EXTERN_METHOD(getPendingVoiceQuery:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(getLocation:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(setArtwork:(NSString *)serverType)
RCT_EXTERN_METHOD(setStationLogo:(NSString *)url)
RCT_EXTERN__BLOCKING_SYNCHRONOUS_METHOD(getDebugInfoSync)
RCT_EXTERN_METHOD(startDiscovery)
RCT_EXTERN_METHOD(stopDiscovery)
@end
