#!/usr/bin/env python3
"""gen-dab-txdb.py — turn a DAB transmitter list into the header the server compiles in.

    python3 tools/gen-dab-txdb.py E1 ~/Downloads/txparamsdab.csv > android/app/src/main/cpp/vibe_dab_txdb_e1.h

The UK source is Ofcom's "Technical parameters for broadcast radio transmitters" (Open
Government Licence): https://www.ofcom.org.uk/spectrum/information/radio-tech-parameters —
the DAB CSV has EID, Site, Transmitter Area, Block, TII Main Id (Hex), TII Sub Id (Hex), Lat, Long.

★ ONE COUNTRY PER FILE, KEYED BY ECC. Stuart, 2026-09-07: "have a DAB transmitter list for each
  country so each country gets the same treatment; the transmitter code we currently have as a
  fallback would be applicable if no transmitter directory available." Another country's list
  goes through the same generator (map its columns below) and lands in vibe_dab_txdb_<ecc>.h —
  or, without a rebuild, in <data dir>/dab-tii-<ecc>.csv as `eid,main,sub,site,area,lat,lon`,
  which the server loads at start (see vibe_dab_txdb.h).
"""
import csv, sys

def main():
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr); sys.exit(2)
    ecc, path = sys.argv[1].upper(), sys.argv[2]
    rows = list(csv.reader(open(path, encoding='utf-8', errors='replace')))
    hdr = [h.strip() for h in rows[0]]
    ix = {h: i for i, h in enumerate(hdr)}
    need = ['EID', 'Site', 'Transmitter Area', 'Block', 'TII Main Id (Hex)', 'TII Sub Id (Hex)', 'Lat', 'Long']
    for n in need:
        if n not in ix: print('missing column', n, file=sys.stderr); sys.exit(1)
    out, seen = [], set()
    for r in rows[1:]:
        try:
            eid = int(r[ix['EID']].strip(), 16)
            main_ = int(r[ix['TII Main Id (Hex)']].strip().strip('"'), 16)
            sub = int(r[ix['TII Sub Id (Hex)']].strip().strip('"'), 16)
            lat = float(r[ix['Lat']]); lon = float(r[ix['Long']])
        except (ValueError, IndexError):
            continue
        site = r[ix['Site']].strip().replace('\\', '').replace('"', "'")
        area = r[ix['Transmitter Area']].strip().replace('\\', '').replace('"', "'")
        key = (eid, main_, sub, round(lat, 3), round(lon, 3))
        if key in seen: continue
        seen.add(key)
        out.append((eid, main_, sub, site, area, lat, lon, r[ix['Block']].strip()))
    out.sort()
    print('// vibe_dab_txdb_%s.h — GENERATED by tools/gen-dab-txdb.py from %s. Do not edit.' % (ecc.lower(), path.split('/')[-1]))
    print('// %d transmitters, ECC %s. Source: Ofcom technical parameters (Open Government Licence v3).' % (len(out), ecc))
    print('#pragma once\n#include "vibe_dab_txdb.h"\nnamespace vibedab {')
    print('inline const DabTx kDabTx_%s[] = {' % ecc)
    for eid, m, s, site, area, lat, lon, blk in out:
        print('    { 0x%04X, %2d, %2d, "%s", "%s", %.5ff, %.5ff, "%s" },' % (eid, m, s, site, area, lat, lon, blk))
    print('};')
    print('inline const size_t kDabTx_%s_n = sizeof(kDabTx_%s) / sizeof(kDabTx_%s[0]);' % (ecc, ecc, ecc))
    print('}  // namespace vibedab')

if __name__ == '__main__':
    main()
